#!/opt/perl/bin/perl

use 5.032;

use strict;
use warnings;
no  warnings 'syntax';

use experimental 'signatures';
use experimental 'lexical_subs';

use POSIX qw [getcwd];

my $DIR  = $ENV {HOME} .
           "/GitHub/Programming_Challenges/perlweeklychallenge-club";
my $ACK  = "/opt/perl/bin/ack";
my $USER = $ENV {USER};

my $dir      = getcwd;
my $language = $dir =~ s!.*/!!r;

my $pattern  = pop;

exec "$ACK -i '$pattern' @ARGV $DIR/challenge-*/$USER/$language/ch-*.*";

__END__
