#!/opt/perl/bin/perl

use 5.032;

use strict;
use warnings;
no  warnings 'syntax';

use experimental 'signatures';
use experimental 'lexical_subs';

use Language::Ook;

my $program = shift // die "Usage $0 <program>";

Language::Ook:: -> new ($program) -> run_code;

__END__
